### PR TITLE
Fix: Skip Redundant deployments typo

### PR DESCRIPTION
**Pull request by liranfarage89**
### Issue & Steps to Reproduce / Feature Request
[//]: <> (choose “resolves” “fixes” or “closes” and put link for the issue)

Fixed SkipRedunantDeployments typo.

### Solution
Fix it.

Update:
- I've found that `number_of_environments_total` was commented out for some reason ( maybe was WIP during that time? )
So I've put it back it and add it to the integration tests.
- Added example too.

### CODE REVIEW

**Comment by liranfarage89** [comment]
[SkipRedundantDeploymenst typo fix](https://trello.com/c/mMt3dwEd/4693-skipredundantdeploymenst-typo-fix)

**Review by omry-hay — APPROVED** [review]
@liranfarage89 - do we also need to update the docs?

**Comment by liranfarage89** [comment]
@omry-hay it depends on whether we want to add an example or not... the docs are ok, the typo was in the code rather than the params.

**Review by eranelbaz — COMMENTED** [review]
Lets up the version

**Pull request merged**
