### PR TITLE
Chore: Integration test for the bug not possible to use OpenTofu as b…

### LINKED ISSUE #975: Bug: Not possible to use OpenTofu as backend binary for Terragrunt
**Describe the bug**
Bug: Not possible to use OpenTofu as backend for Terragrunt

**To Reproduce**

When declaring the resource:

```tf
resource "env0_environment" "live" {
  name                      = "live"
  project_id                = env0_project.administration.id
  is_remote_backend         = false
  deploy_on_push            = true
  run_plan_on_pull_requests = true
  vcs_pr_comments_enabled   = true
  force_destroy             = true

  variable_sets = [env0_variable_set.live.id]

  without_template_settings {
    description            = "Core Azure"
    github_installation_id = var.github_installation_id
    repository             = var.infrastructure_repository_url
    path                   = "live"
    opentofu_version       = "1.8.1"
    terragrunt_version     = "0.64.5"
    type                   = "terragrunt"
    revision               = "feature/base-env0-structure"
    is_terragrunt_run_all  = true
    terragrunt_tf_binary   = "opentofu"
  }
}
```

it throws an error:

`Error: could not create environment: 400 Bad Request: can't create a template with undefined terraform version value`

It works just fine if you switch `opentofu_version` with `terraform_version`.

**Expected behavior**

Using the terraform provider, with type = "terragrunt" and with terragrunt_tf_binary = "opentofu" should work.

**Provider Version**
All

**Screenshots**

image

**Additional context**
The fix for this issue was already worked on the env0's API

### PR DESCRIPTION
**Pull request by TomerHeber**
…ackend for Terragrunt via env0 Terraform provider (#974)

* chore: Integration test for the bug not possible to use OpenTofu as backend for Terragrunt via env0 Terraform provider

* chore: Integration test for the bug not possible to use OpenTofu as backend for Terragrunt via env0 Terraform provider

### Issue & Steps to Reproduce / Feature Request
resolves #975 

### Solution

Add an integration test to reproduce an issue.

### CODE REVIEW

**Comment by TomerHeber** [comment]
hi @onhate 

It looks like the test has failed:

```
Error: -12T14:39:23.816Z [ERROR] provider.terraform-provider-env0: Response contains error diagnostic: @caller=/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/diag/diagnostics.go:62 diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=5.4 tf_req_id=4f39ca40-25ce-7610-6fc2-fab2e4820be9 tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_summary="could not create environment: 400 Bad Request: can't create a template with undefined terraform version value" tf_provider_addr=provider tf_resource_type=env0_environment timestamp=2024-11-12T14:39:23.815Z
╷
│ Error: could not create environment: 400 Bad Request: can't create a template with undefined terraform version value
│ 
│   with env0_environment.environment,
│   on main.tf line 14, in resource "env0_environment" "environment":
│   14: resource "env0_environment" "environment" {
│ 
╵
```

Is this what you expected?

CC - @yaronya

**Comment by onhate** [comment]
yes, that's the expected behavior until the fix is release to production on env0 APIs.

**Comment by razbensimon** [comment]
@TomerHeber BE side merged, please check and continue :)

**Review by razbensimon — APPROVED** [review]

**Pull request merged**
