### PR TITLE
Fix: fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
### Solution

Found few misspellings.
Many bombs were defused 💣

Please use https://github.com/crate-ci/typos at Env0

### CODE REVIEW

**Comment by TomerHeber** [comment]
Hi @szepeviktor - thank you for the PR.


CI / Unit Tests (pull_request) -

**Comment by szepeviktor** [comment]
@TomerHeber Not interested in these changes?

**Comment by szepeviktor** [comment]
CI fails because secrets are not available for PRs from forks.
https://github.com/env0/terraform-provider-env0/blob/1afd6991882fcfd77f5dcd7e5b00851ae9ca523c/.github/workflows/ci.yml#L7-L10

**Comment by TomerHeber** [comment]
Hi @szepeviktor - 

Thank you for the PR.

I am very interested in this fix.
However, I need to figure out how I can get the pipelines to the path from the remote branch.

**Pull request merged**
