### PR TITLE
Fix: Adjust Configuration api

### LINKED ISSUE #24: Can't create/update configuration variables
Create/Update configuration variables fails with `body is not an array`, as we aren't really sending the request as an array and API schema has changed recently.

### PR DESCRIPTION
**Pull request by avnerenv0**
Configuration API is now Array-only
Adjusted that

closes #24

### CODE REVIEW

**Comment by avnerenv0** [comment]
[TF Provider - can't create/update configuration variables](https://trello.com/c/fvSSWpiE/3309-tf-provider-cant-create-update-configuration-variables)

**Review by eranelbaz — COMMENTED** [review]
Question, i see you make a lot of `[0]` 
can't we multiple CRUD using terraform?

**Comment by avnerenv0** [comment]
> Question, i see you make a lot of `[0]`
> can't we multiple CRUD using terraform?

We can do anything we are writing the code :)
But in this case it makes sense to have a "Configuration Property" resource that is singular, and it's also how TF providers are usually designed. The TF resources try to be 'independant' so we can't make one API call for multiple resource instances.

Our API is getting/giving arrays, so to play nice with a singular resource I had to `[0]`

**Review by roni-frantchi — APPROVED** [review]
> Our API is getting/giving arrays, so to play nice with a singular resource I had to [0]

Consider checking if >1 and log/warn/throw

**Comment by avnerenv0** [comment]
> > Our API is getting/giving arrays, so to play nice with a singular resource I had to [0]
> 
> Consider checking if >1 and log/warn/throw

Since it's create/update and I'm also the one making the request (unlike find-by-name cases), I'm ok with leaving as is

**Pull request merged**
