### PR TITLE
fix: integration tests templates must enforce terraform_tf_binary

### LINKED ISSUE #975: Bug: Not possible to use OpenTofu as backend binary for Terragrunt
**Describe the bug**
Bug: Not possible to use OpenTofu as backend for Terragrunt

**To Reproduce**

When declaring the resource:

```tf
resource "env0_environment" "live" {
  name                      = "live"
  project_id                = env0_project.administration.id
  is_remote_backend         = false
  deploy_on_push            = true
  run_plan_on_pull_requests = true
  vcs_pr_comments_enabled   = true
  force_destroy             = true

  variable_sets = [env0_variable_set.live.id]

  without_template_settings {
    description            = "Core Azure"
    github_installation_id = var.github_installation_id
    repository             = var.infrastructure_repository_url
    path                   = "live"
    opentofu_version       = "1.8.1"
    terragrunt_version     = "0.64.5"
    type                   = "terragrunt"
    revision               = "feature/base-env0-structure"
    is_terragrunt_run_all  = true
    terragrunt_tf_binary   = "opentofu"
  }
}
```

it throws an error:

`Error: could not create environment: 400 Bad Request: can't create a template with undefined terraform version value`

It works just fine if you switch `opentofu_version` with `terraform_version`.

**Expected behavior**

Using the terraform provider, with type = "terragrunt" and with terragrunt_tf_binary = "opentofu" should work.

**Provider Version**
All

**Screenshots**

image

**Additional context**
The fix for this issue was already worked on the env0's API

### PR DESCRIPTION
**Pull request by onhate**
### Issue & Steps to Reproduce / Feature Request

A change on env0's API requires to enforce the `terraform_tf_binary` when `terraform_version` is specified.

Fixes #975

### Solution

Enforce `terraform_tf_binary`

### CODE REVIEW

**Review by razbensimon — APPROVED** [review]

**Comment by razbensimon** [comment]
FYI @TomerHeber

**Comment by TomerHeber** [comment]
Hi @razbensimon - you shouldn't have merged it since tests are failing.
But it's alright... I'll fix it later in the week.

**Comment by razbensimon** [comment]
How did it let me? @TomerHeber 
it ran a CI test. Where did I miss it?

**Comment by razbensimon** [comment]
@TomerHeber I afraid it may cause env0 pipeline to be blocked. I am checking.. 
so maybe we should revert now

**Comment by TomerHeber** [comment]
@razbensimon - running a dummy PR to confirm
https://github.com/env0/terraform-provider-env0/pull/978

if it passes we're good.

**Comment by TomerHeber** [comment]
@razbensimon - looks like it passed. So false alarm. I was probably looking at an old failure.

**Comment by razbensimon** [comment]
yes just confirmed too.
from env0 pipeline:
```
2024/11/14 18:36:18 Completed successfully terraform [apply -auto-approve -var second_run=0] in 004_template
```

Thanks for checking too! @TomerHeber

**Pull request merged**
