### PR TITLE
Feat: add support for Terragrunt working directory (#233)

### LINKED ISSUE #233: Terragrunt Working Directory support
Please add TF working directory to env0 environment resource.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
resolves #233 

### Solution
Added "terragrunt_working_directory" to the environment resource schema.
Updated the models.
Updated the unit tests.

### CODE REVIEW

**Review by yaronya — COMMENTED** [review]
LGTM
Can you please also add integration tests for this attribute? I think we already have a setup for the `environment` resource so you can just add this attribute there (both for create and update, if supported)

**Comment by TomerHeber** [comment]
> LGTM Can you please also add integration tests for this attribute? I think we already have a setup for the `environment` resource so you can just add this attribute there (both for create and update, if supported)

@yaronya - do you have some time for guidance on this? (great if you have time for a quick session).
I can't use 012_environment test, because it's for Terraform.
So I guess there are a couple of options:
1. create a new integration test (017).
2. Use 012, but add more resources to existing to it.

Just looking for guidance on best practices. Thanks!

**Comment by yaronya** [comment]
@TomerHeber so IMO since we're still in the context of the `environment` resource for this integration test, I suggest to keep the existing 012 TF setup and simply add a TG template + environment to it. I think that we'd usually want to keep all relevant scenarios for a resource type in the same TF setup, so long it doesn't become too big.

Feel free to call me via our Slack channel for a quick session 👍

**Comment by TomerHeber** [comment]
@yaronya - I added integration tests.
See https://github.com/env0/terraform-provider-env0/pull/260/commits/d1770d1549e572a579737fb32b204e1911655fd2

**Comment by TomerHeber** [comment]
> @yaronya - I added integration tests. See [d1770d1](https://github.com/env0/terraform-provider-env0/commit/d1770d1549e572a579737fb32b204e1911655fd2)

**Comment by TomerHeber** [comment]
> @yaronya - I added integration tests. See [d1770d1](https://github.com/env0/terraform-provider-env0/commit/d1770d1549e572a579737fb32b204e1911655fd2)

@yaronya also https://github.com/env0/terraform-provider-env0/pull/260/commits/f3374e81f276ef2c1b8375e8482ae706f4bc93f4

Weird it didn't fail for me locally. Any idea why?

**Review by yaronya — APPROVED** [review]

**Pull request merged**
