### PR TITLE
Fix: failing API client tests

### PR DESCRIPTION
**Pull request by yaronya**
### Issue & Steps to Reproduce / Feature Request
Template API client tests are failing.

### Solution
1. Add missing methods to `ApiClientInterface`
2. Regenerate mocks

### CODE REVIEW

**Comment by eranelbaz** [comment]
Can we somehow auto generate the mocks?
maybe hook for the `go build` command?

**Comment by yaronya** [comment]
@eranelbaz we can open an issue for that, this is out of scope for this PR. Please approve 🙏

**Review by avnerenv0 — APPROVED** [review]
so the CI failed and we merged anyway?

**Comment by yaronya** [comment]
> so the CI failed and we merged anyway?

@avnerenv0 yes 😞 
But I've added it to required status checks now so won't happen again 🚫

**Pull request merged**
