### PR TITLE
Fix: externalID-white-spaces

### PR DESCRIPTION
**Pull request by samuel-br**
### Issue & Steps to Reproduce / Feature Request
[//]: <> (choose “resolves” “fixes” or “closes” and put link for the issue)
fixes https://github.com/env0/terraform-provider-env0/issues/513
### Solution
remove white space from every value assign to `External id`

### CODE REVIEW

**Comment by samuel-br** [comment]
[Change TF provider integration test when value contain white space is assigned to AWS 'External Id'](https://trello.com/c/t9kbeN7u/7828-change-tf-provider-integration-test-when-value-contain-white-space-is-assigned-to-aws-external-id)

**Comment by TomerHeber** [comment]
@samuel-br  - just so I understand:
External ID with whitespaces is valid. But on your code, you added something that will throw an error if there is a whitespace?

**Comment by samuel-br** [comment]
AWS wont allowed white spaces, we add this validation today to the backend, what makes the tests fail

**Comment by TomerHeber** [comment]
> AWS wont allowed white spaces, we add this validation today to the backend, what makes the tests fail

@samuel-br - Understood. should it be validated in SDK as well. WDYT?

**Comment by samuel-br** [comment]
> > AWS wont allowed white spaces, we add this validation today to the backend, what makes the tests fail
> 
> @samuel-br - Understood. should it be validated in SDK as well. WDYT?

For what I know, @yaronya planed to, so I belive ticket will be add next day

**Review by TomerHeber — APPROVED** [review]
LGTM!

**Comment by yaronya** [comment]
> For what I know, @yaronya planed to, so I belive ticket will be add next day

@samuel-br Please add this as a GH issue

**Pull request merged**
