### PR TITLE
Fix: show error instead of empty string

### PR DESCRIPTION
**Pull request by sabasabo**
### Issue & Steps to Reproduce / Feature Request
Hiding the error

### Solution
Returning the error

### CODE REVIEW

**Review by yaronya — CHANGES_REQUESTED** [review]
Please add some test that covers it

**Review by roni-frantchi — COMMENTED** [review]
Also - please add proper motivation to the PR @sabasabo please.

**Comment by sabasabo** [comment]
@yaronya @liranfarage89 @roni-frantchi 
I'm closing this pr and opening a ticket to BOTF with all the details (WalkMe).
I thought it will take me a few minutes to add the test, but I'm not familiar enough with Go to do so.

**Comment by roni-frantchi** [comment]
@sabasabo let's start with sharing on Slack what this is about please.

**Comment by liranfarage89** [comment]
@sabasabo you could ask for help in Slack... it's actually a good opportunity to do an "intro task" in the provider. If you don't want to deal with it, at least we should open an issue regarding that, but I do believe it will help you with knowing our provider.

**Comment by sabasabo** [comment]
@liranfarage89 I understand, but I want to focus on one task at a time. 
I'm currently working on the Sentry alerts task,

**Pull request closed without merging**
