### PR TITLE
Fix: do not retry for 4xx errors

### LINKED ISSUE #949: Extra api call retries for 422
**Describe the bug**
When we fail to create an environment and we get 422 we retry it although there is no need as this is not server side issue

**To Reproduce**
```
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

provider "env0" {
}

resource "random_uuid" "workspace" {
}

resource "env0_environment" "example" {
  name                = "environment"
  project_id          = "."
  template_id         = "."
  prevent_auto_deploy = true

  sub_environment_configuration {
    alias = "first-alias"
    configuration {
      name          = "broken-hcl"
      value         = "{"
      schema_format = "HCL"
    }
    revision = "master"
    workspace = random_uuid.workspace.result
  }
}
```
Logs - 
```
2024-09-05T15:08:08.841+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: @module=provider.env0_api_client method=POST status="422 Unprocessable Entity" url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 timestamp="2024-09-05T15:08:08.840+0200"
2024-09-05T15:08:09.842+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Sending request: method=POST url=/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:194 @module=provider.env0_api_client timestamp="2024-09-05T15:08:09.841+0200"
2024-09-05T15:08:12.948+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 @module=provider.env0_api_client method=POST status="422 Unprocessable Entity" timestamp="2024-09-05T15:08:12.947+0200"
2024-09-05T15:08:14.102+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Sending request: @module=provider.env0_api_client method=POST url=/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:194 timestamp="2024-09-05T15:08:14.102+0200"
env0_environment.example: Still creating... [10s elapsed]
2024-09-05T15:08:17.151+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 @module=provider.env0_api_client method=POST status="422 Unprocessable Entity" timestamp="2024-09-05T15:08:17.150+0200"
2024-09-05T15:08:19.515+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Sending request: @caller=github.com/env0/terraform-provider-env0/env0/provider.go:194 @module=provider.env0_api_client method=POST url=/environments timestamp="2024-09-05T15:08:19.515+0200"
2024-09-05T15:08:22.416+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: @module=provider.env0_api_client method=POST status="422 Unprocessable Entity" url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 timestamp="2024-09-05T15:08:22.416+0200"
env0_environment.example: Still creating... [20s elapsed]
2024-09-05T15:08:26.135+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Sending request: url=/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:194 @module=provider.env0_api_client method=POST timestamp="2024-09-05T15:08:26.134+0200"
2024-09-05T15:08:29.092+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: status="422 Unprocessable Entity" url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 @module=provider.env0_api_client method=POST timestamp="2024-09-05T15:08:29.092+0200"
2024-09-05T15:08:33.686+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Sending request: @caller=github.com/env0/terraform-provider-env0/env0/provider.go:194 @module=provider.env0_api_client method=POST url=/environments timestamp="2024-09-05T15:08:33.686+0200"
env0_environment.example: Still creating... [30s elapsed]
2024-09-05T15:08:36.584+0200 [INFO]  provider.terraform-provider-env0_v1.20.7: Received response: status="422 Unprocessable Entity" url=https://api.env0.com/environments @caller=github.com/env0/terraform-provider-env0/env0/provider.go:199 @module=provider.env0_api_client method=POST timestamp="2024-09-05T15:08:36.584+0200"
2024-09-05T15:08:36.585+0200 [ERROR] provider.terraform-provider-env0_v1.20.7: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/diag/diagnostics.go:62 @module=sdk.proto tf_resource_type=env0_environment tf_proto_version=5.4 tf_req_id=11c9bfa9-c3ff-5cfb-952e-336a195aebbf tf_rpc=ApplyResourceChange diagnostic_detail="" diagnostic_severity=ERROR diagnostic_summary="could not create environment: 422 Unprocessable Entity: Error in variable arel: failed to parse content as HCL: parse config: [HCL:1,6-7: Unclosed configuration block; There is no closing brace for this block before the end of the file. This may be caused by incorrect brace nesting elsewhere in this file.]" tf_provider_addr=provider timestamp="2024-09-05T15:08:36.585+0200"
```

**Expected behavior**
It should only send one API call

**Provider Version**
1.20.7

**Additional context**

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #949 

### Solution

Removed the default error handler.

### CODE REVIEW

**Review by RLRabinowitz — COMMENTED** [review]
Can we add a test for this please?

**Comment by TomerHeber** [comment]
> Can we add a test for this please?

I have checked... right now there are no tests for the provider http client.
Adding these is an effort, but I'm not not sure we would gain anything from it.

There are these tests: client/http/client_test.go - but they don't really test the provider client... (which is created in providor.go).

I guess the question is: what are we trying to test?

we could test this specific function, by passing multiple responses with different status codes:
```
			AddRetryCondition(func(r *resty.Response, err error) bool {
				if r == nil {
					// No response. Possibly a networking issue (E.g. DNS lookup failure).
					tflog.SubsystemWarn(subCtx, "env0_api_client", "No response, retrying request")
					return true
				}

				// When running integration tests 404 may occur due to "database eventual consistency".
				// Retry when there's a 5xx error. Otherwise do not retry.
				if r.StatusCode() >= 500 || (isIntegrationTest && r.StatusCode() == 404) {
					tflog.SubsystemWarn(subCtx, "env0_api_client", "Received a failed or not found response, retrying request", map[string]interface{}{"method": r.Request.Method, "url": r.Request.URL, "status code": r.StatusCode()})
					return true
				}

				if r.StatusCode() == 200 && isIntegrationTest && r.String() == "[]" {
					tflog.SubsystemWarn(subCtx, "env0_api_client", "Received an empty list , retrying request", map[string]interface{}{"method": r.Request.Method, "url": r.Request.URL})
					return true
				}

				return false
			})
```

move this code a dedicated, function... then write unit tests that each test case passes a different response object to this function.

Let me know if it's something you would like to me to do.

**Comment by avnerenv0** [comment]
Didn't we add this to make the integration tests more stable?
Like we had issues with weak consistency and we needed the retries for them to pass?

**Comment by TomerHeber** [comment]
> Didn't we add this to make the integration tests more stable? Like we had issues with weak consistency and we needed the retries for them to pass?

@avnerenv0 

We did...
The question is: if you expect customers to run into the same eventual consistency issues?
If the answer is 'yes', I may want to make some additional (minor) modifications.

**Comment by TomerHeber** [comment]
> > Didn't we add this to make the integration tests more stable? Like we had issues with weak consistency and we needed the retries for them to pass?
> 
> @avnerenv0
> 
> We did... The question is: if you expect customers to run into the same eventual consistency issues? If the answer is 'yes', I may want to make some additional (minor) modifications.

I removed the line that would retry for any error... and kept the one that retries only on specific use-cases.
But if 404 'false-positive' is something customers may encounter as well... I would like to expend it not just for integration tests.

**Comment by avnerenv0** [comment]
no that's ok. 
The integration tests sometimes create a resource and try to read it in the same file, that's not a pattern we need to support in real life. 

@RLRabinowitz I'm good with this PR but I saw you also commented, so please approve if you are fine with the response.

**Comment by RLRabinowitz** [comment]
> I guess the question is: what are we trying to test?

Well, we want to make sure that we are not retrying any 4xx HTTP errors, right? Make sure the scenario mentioned in the issue will not happen again.
In this specific example - if a `deploy` fails with 4xx, we shouldn't retry it

Adding a UT on the retry condition doesn't really help, as the fix was unrelated to that code.

Ideally we'd have a test that actually makes sure that this doesn't happen again, as right now we have no guardrails saving us from this happening again

Couldn't such a test simply be added to `client_test.go`?

**Comment by TomerHeber** [comment]
> > I guess the question is: what are we trying to test?
> 
> Well, we want to make sure that we are not retrying any 4xx HTTP errors, right? Make sure the scenario mentioned in the issue will not happen again. In this specific example - if a `deploy` fails with 4xx, we shouldn't retry it
> 
> Adding a UT on the retry condition doesn't really help, as the fix was unrelated to that code.
> 
> Ideally we'd have a test that actually makes sure that this doesn't happen again, as right now we have no guardrails saving us from this happening again
> 
> Couldn't such a test simply be added to `client_test.go`?

Ok sure.
I'll have to modify client_test.go since it tests an empty resty instance and not the one used by the provider.
This will require some minor refactoring but nothing too big. (I hope).

**Comment by TomerHeber** [comment]
> > > I guess the question is: what are we trying to test?
> > 
> > 
> > Well, we want to make sure that we are not retrying any 4xx HTTP errors, right? Make sure the scenario mentioned in the issue will not happen again. In this specific example - if a `deploy` fails with 4xx, we shouldn't retry it
> > Adding a UT on the retry condition doesn't really help, as the fix was unrelated to that code.
> > Ideally we'd have a test that actually makes sure that this doesn't happen again, as right now we have no guardrails saving us from this happening again
> > Couldn't such a test simply be added to `client_test.go`?
> 
> Ok sure. I'll have to modify client_test.go since it tests an empty resty instance and not the one used by the provider. This will require some minor refactoring but nothing too big. (I hope).

@RLRabinowitz I have added unit tests as requested.

**Review by RLRabinowitz — APPROVED** [review]

**Pull request merged**
