### PR TITLE
Feat add gcp cloud credentials

### LINKED ISSUE #248: Support new GCP & Azure credentials
### New `gcp_credentials` resource:

- Should call same create/list/delete APIs as `aws_credentials` resource, but with type `GCP_SERVICE_ACCOUNT_DEPLOYMENT`
- Fields should be `project_id` and `service_account_key`, on API calls `value` should be an object of those fields. `service_account_key` should be secret
- When importing, only accept credentials that are GCP (`GCP_SERVICE_ACCOUNT_DEPLOYMENT`). This is can be done in a separate issue though

### New `azure_credentials` resource:

- Should call same create/list/delete APIs as `aws_credentials` resource, but with type `AZURE_SERVICE_PRINCIPAL_FOR_DEPLOYMENT`
- Fields should be `clientId`, `clientSecret`, `tenantId` and `subscriptionId`, on API calls `value` should be an object of those fields. `clientSecret` should be secret
- When importing, only accept credentials that are AZURE (`AZURE_SERVICE_PRINCIPAL_FOR_DEPLOYMENT`). This is can be done in a separate issue though

### PR DESCRIPTION
**Pull request by liranfarage89**
### Issue & Steps to Reproduce / Feature Request
Adding  GCP cloud credentials ( next PR will be azure )

resolves #248

### Solution
Add it. 
- Reuse aws HTTP client
- Do not add `Import` since the API doesn't return the credentials values

### CODE REVIEW

**Comment by liranfarage89** [comment]
[Add Support for GCP and Azure credentials in our Terraform provider](https://trello.com/c/SCz0Q494/5651-add-support-for-gcp-and-azure-credentials-in-our-terraform-provider)

**Comment by yaronya** [comment]
@liranfarage89 please make sure to [properly link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) this PR to relevant issue (using "resolves" or "closes" keywords)

**Review by GiliFaroEnv0 — COMMENTED** [review]
Looks good to me BUT add integration test
maybe rename the was one and do a general one for all the credentials

**Review by GiliFaroEnv0 — APPROVED** [review]
LGTM

**Pull request merged**
