### PR TITLE
Fix: env0_environment resource - cannot re-enable vcs

### LINKED ISSUE #962: Bug - env0_environment resource - cannot re-enable vcs
**Describe the bug**
when you create an env0_environment that is not integrated to a vcs repository you cannot enable repository integration afterward.

**To Reproduce**
# create without VCS
resource "env0_environment" "test" {
  name = "non-vcs-test"

  auto_deploy_on_path_changes_only = false
  deploy_on_push = false
  run_plan_on_pull_requests = false

  without_template_settings {
    is_gitlab        = false
    repository       = "https://.git"
    token_name       = var.git_token_name
    token_id         = var.git_token_id
    type             = "opentofu"
    opentofu_version = "latest"
  }
}

# enabling VCS afterward
resource "env0_environment" "test" {
  name = "non-vcs-test"

  auto_deploy_on_path_changes_only = true
  deploy_on_push = true
  run_plan_on_pull_requests = true

  without_template_settings {
    is_gitlab        = true
    repository       = "https://gitlab.com/test-repo.git"
    token_name       = var.git_token_name
    token_id         = var.git_token_id
    type             = "opentofu"
    opentofu_version = "latest"
  }
}
# gives following error:
│ Error: could not update environment: 400 Bad Request: Can't set continuousDeployment & autoDeployOnPathChangesOnly & pullRequestPlanDeployments for an environment originated from a non vcs-integrated template.
│ Suggestion: add VCS parameter such as githubInstallationId, or isGitLab.
│ 
│   with env0_environment.test,
│   on main.tf line 5, in resource "env0_environment" "test":
│    5: resource "env0_environment" "test" {

**Expected behavior**
Be able to enable VCS parameters after creation of the environment, use cases are migration of workspaces from TFC or just plan upgrading of a legacy environment.

**Provider Version**
Latest, no lock

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #962 

### Solution

Modified the order of calls. Updating the template occurs first.

### CODE REVIEW

**Comment by Wassap124** [comment]
can you add a test that validates the bug does not occur?

**Comment by TomerHeber** [comment]
> can you add a test that validates the bug is resolved?

@Wassap124 - it's an excellent idea.
Unfortunatly, testing via acceptance test is not helpful.
I will have to add a harness test instead. I will check that option, and revert back.

**Comment by TomerHeber** [comment]
> > can you add a test that validates the bug is resolved?
> 
> @Wassap124 - it's an excellent idea. Unfortunatly, testing via acceptance test is not helpful. I will have to add a harness test instead. I will check that option, and revert back.

@Wassap124 - I have added a test to the harness tests. No issues (:

**Review by GiliFaroEnv0 — APPROVED** [review]
Nice solution

**Pull request merged**
